version: '3.8'

services:
  postgres:
    image: postgres:17.0
    container_name: postgres_dpom
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dpom
    volumes:
      - pgdata:/var/lib/postgresql/data
      #      - ./pgdata_backup:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_dpom
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - postgres
volumes:
  pgdata:
  pgdata_backup:
